### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by singingtelegram**
I'm a Chinese Botballer, from Hefei No.42 Middle School. I've made some corrections and improvements to the original translation.

### CODE REVIEW

**Comment by jsoutherland** [comment]
@navzam Do you know where we left off on this?  I saw we were emailing with Mao about translations in March after this PR was submitted.  

There are merge conflicts now and I see that master is missing these changes
(for example we have the original line at https://github.com/kipr/botui/blob/master/ts/botui_zh.ts#L169)

**Comment by navzam** [comment]
@jsoutherland It looks like we last updated the Chinese translations in 8efc11d, almost two months after this pull request. I remember not merging this in until we verified with Mao, but he gave us the OK to do so. I'll take a look at the conflicts later tonight.

**Comment by Zacharyprime** [comment]
Does anyone know if this pull request is still necessary?
I'm fairly certain this issue has already been solved.

**Comment by Zacharyprime** [comment]
I am going to confirm this as a stale branch and close this thread because while I don't understand Chinese well enough to check the translations, it seems pretty clear that we've worked this out already.

If I'm mistaken please reopen this with the merge conflicts fixed.

**Pull request closed without merging**
